/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacote.visao;

import pacote.dominio.Avaliacao;
import pacote.visao.avaliacao.avaliacaoCadastrar;
import pacote.visao.avaliacao.avaliacaoDeletar;
import pacote.visao.avaliacao.avaliacaoEditar;
import pacote.visao.avaliacao.avaliacaoVisualizar;
import pacote.visao.clinica.clinicaAtualizar;
import pacote.visao.clinica.clinicaCadastrar;
import pacote.visao.clinica.clinicaDeletar;
import pacote.visao.clinica.clinicaVisualizar;
import pacote.visao.consulta.consultaCadastrar;
import pacote.visao.consulta.consultaDeletar;
import pacote.visao.consulta.consultaEditar;
import pacote.visao.consulta.consultaVisualizar;
import pacote.visao.fisioterapeuta.fisioterapeutaCadastrar;
import pacote.visao.fisioterapeuta.fisioterapeutaDeletar;
import pacote.visao.fisioterapeuta.fisioterapeutaEditar;
import pacote.visao.fisioterapeuta.fisioterapeutaVisualizar;
import pacote.visao.paciente.pacienteCadastrar;
import pacote.visao.paciente.pacienteDeletar;
import pacote.visao.paciente.pacienteEditar;
import pacote.visao.paciente.pacienteVisualizar;

/**
 *
 * @author LEO
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemMenuCadastrarClinica = new javax.swing.JMenuItem();
        itemVisualizarClinica = new javax.swing.JMenuItem();
        itemEditarClinica = new javax.swing.JMenuItem();
        itemDeletarClinica = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemMenuCadastrarFisioterapeuta = new javax.swing.JMenuItem();
        itemVisualizarFisioterapeutas = new javax.swing.JMenuItem();
        itemEditarFisioterapeuta = new javax.swing.JMenuItem();
        itemDeletarFisioterapeuta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemMenuCadastrarPaciente = new javax.swing.JMenuItem();
        itemVisualizarPaciente = new javax.swing.JMenuItem();
        itemEditarPaciente = new javax.swing.JMenuItem();
        itemDeletarPaciente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemCadastrarConsulta = new javax.swing.JMenuItem();
        itemVisualizarConsultas = new javax.swing.JMenuItem();
        itemEditarConsulta = new javax.swing.JMenuItem();
        itemDeletarConsulta = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itemCadastrarAvaliacao = new javax.swing.JMenuItem();
        itemVisulizarAvaliacao = new javax.swing.JMenuItem();
        itemEditarAvaliacao = new javax.swing.JMenuItem();
        itemDeletarAvaliacao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRINCIPAL");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/img/fis.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSair))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSair))
        );

        jMenu1.setText("Clinica");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        itemMenuCadastrarClinica.setText("Nova Clinica");
        itemMenuCadastrarClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastrarClinicaActionPerformed(evt);
            }
        });
        jMenu1.add(itemMenuCadastrarClinica);

        itemVisualizarClinica.setText("Visualizar clinicas");
        itemVisualizarClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVisualizarClinicaActionPerformed(evt);
            }
        });
        jMenu1.add(itemVisualizarClinica);

        itemEditarClinica.setText("Editar Clinica");
        itemEditarClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarClinicaActionPerformed(evt);
            }
        });
        jMenu1.add(itemEditarClinica);

        itemDeletarClinica.setText("Deletar clinica");
        itemDeletarClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeletarClinicaActionPerformed(evt);
            }
        });
        jMenu1.add(itemDeletarClinica);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Fisioterapeuta");

        itemMenuCadastrarFisioterapeuta.setText("Cadastrar Fisioterapeuta");
        itemMenuCadastrarFisioterapeuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastrarFisioterapeutaActionPerformed(evt);
            }
        });
        jMenu2.add(itemMenuCadastrarFisioterapeuta);

        itemVisualizarFisioterapeutas.setText("Visualizar fisioterapeutas");
        itemVisualizarFisioterapeutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVisualizarFisioterapeutasActionPerformed(evt);
            }
        });
        jMenu2.add(itemVisualizarFisioterapeutas);

        itemEditarFisioterapeuta.setText("Editar fisioterapeuta");
        itemEditarFisioterapeuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarFisioterapeutaActionPerformed(evt);
            }
        });
        jMenu2.add(itemEditarFisioterapeuta);

        itemDeletarFisioterapeuta.setText("Deletar fisioterapeuta");
        itemDeletarFisioterapeuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeletarFisioterapeutaActionPerformed(evt);
            }
        });
        jMenu2.add(itemDeletarFisioterapeuta);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Paciente");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        itemMenuCadastrarPaciente.setText("Cadastrar Paciente");
        itemMenuCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastrarPacienteActionPerformed(evt);
            }
        });
        jMenu3.add(itemMenuCadastrarPaciente);

        itemVisualizarPaciente.setText("Visualizar pacientes cadastrados");
        itemVisualizarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVisualizarPacienteActionPerformed(evt);
            }
        });
        jMenu3.add(itemVisualizarPaciente);

        itemEditarPaciente.setText("Editar cadastro paciente");
        itemEditarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarPacienteActionPerformed(evt);
            }
        });
        jMenu3.add(itemEditarPaciente);

        itemDeletarPaciente.setText("Deletar cadastro paciente");
        itemDeletarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeletarPacienteActionPerformed(evt);
            }
        });
        jMenu3.add(itemDeletarPaciente);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consulta");

        itemCadastrarConsulta.setText("Agendar consulta");
        itemCadastrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarConsultaActionPerformed(evt);
            }
        });
        jMenu4.add(itemCadastrarConsulta);

        itemVisualizarConsultas.setText("Visualizar consultas");
        itemVisualizarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVisualizarConsultasActionPerformed(evt);
            }
        });
        jMenu4.add(itemVisualizarConsultas);

        itemEditarConsulta.setText("Editar Consulta");
        itemEditarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarConsultaActionPerformed(evt);
            }
        });
        jMenu4.add(itemEditarConsulta);

        itemDeletarConsulta.setText("Deletar consulta");
        itemDeletarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeletarConsultaActionPerformed(evt);
            }
        });
        jMenu4.add(itemDeletarConsulta);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Avaliacao");

        itemCadastrarAvaliacao.setText("Adicionar avaliação");
        itemCadastrarAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarAvaliacaoActionPerformed(evt);
            }
        });
        jMenu5.add(itemCadastrarAvaliacao);

        itemVisulizarAvaliacao.setText("Visualizar avaliações");
        itemVisulizarAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVisulizarAvaliacaoActionPerformed(evt);
            }
        });
        jMenu5.add(itemVisulizarAvaliacao);

        itemEditarAvaliacao.setText("Editar avaliação");
        itemEditarAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarAvaliacaoActionPerformed(evt);
            }
        });
        jMenu5.add(itemEditarAvaliacao);

        itemDeletarAvaliacao.setText("Deletar avaliação");
        itemDeletarAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeletarAvaliacaoActionPerformed(evt);
            }
        });
        jMenu5.add(itemDeletarAvaliacao);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void itemMenuCadastrarClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastrarClinicaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new clinicaCadastrar().setVisible(true);
    }//GEN-LAST:event_itemMenuCadastrarClinicaActionPerformed

    private void itemMenuCadastrarFisioterapeutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastrarFisioterapeutaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new fisioterapeutaCadastrar().setVisible(true);
    }//GEN-LAST:event_itemMenuCadastrarFisioterapeutaActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void itemMenuCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastrarPacienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new pacienteCadastrar().setVisible(true);
    }//GEN-LAST:event_itemMenuCadastrarPacienteActionPerformed

    private void itemCadastrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarConsultaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new consultaCadastrar().setVisible(true);
    }//GEN-LAST:event_itemCadastrarConsultaActionPerformed

    private void itemCadastrarAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarAvaliacaoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new avaliacaoCadastrar().setVisible(true);
    }//GEN-LAST:event_itemCadastrarAvaliacaoActionPerformed

    private void itemVisualizarClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVisualizarClinicaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new clinicaVisualizar().setVisible(true);
    }//GEN-LAST:event_itemVisualizarClinicaActionPerformed

    private void itemVisualizarFisioterapeutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVisualizarFisioterapeutasActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new fisioterapeutaVisualizar().setVisible(true);
    }//GEN-LAST:event_itemVisualizarFisioterapeutasActionPerformed

    private void itemVisualizarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVisualizarPacienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new pacienteVisualizar().setVisible(true);
    }//GEN-LAST:event_itemVisualizarPacienteActionPerformed

    private void itemVisualizarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVisualizarConsultasActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new consultaVisualizar().setVisible(true);
    }//GEN-LAST:event_itemVisualizarConsultasActionPerformed

    private void itemVisulizarAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVisulizarAvaliacaoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new avaliacaoVisualizar().setVisible(true);
    }//GEN-LAST:event_itemVisulizarAvaliacaoActionPerformed

    private void itemEditarClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarClinicaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new clinicaAtualizar().setVisible(true);
    }//GEN-LAST:event_itemEditarClinicaActionPerformed

    private void itemEditarFisioterapeutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarFisioterapeutaActionPerformed
        // TODO add your handling code here:
        this.dispose();
       new fisioterapeutaEditar().setVisible(true);
    }//GEN-LAST:event_itemEditarFisioterapeutaActionPerformed

    private void itemEditarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarPacienteActionPerformed
        // TODO add your handling code here:
        dispose();
        new pacienteEditar().setVisible(true);
    }//GEN-LAST:event_itemEditarPacienteActionPerformed

    private void itemEditarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarConsultaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new consultaEditar().setVisible(true);
    }//GEN-LAST:event_itemEditarConsultaActionPerformed

    private void itemEditarAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarAvaliacaoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new avaliacaoEditar().setVisible(true);
    }//GEN-LAST:event_itemEditarAvaliacaoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void itemDeletarClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeletarClinicaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new clinicaDeletar().setVisible(true);
    }//GEN-LAST:event_itemDeletarClinicaActionPerformed

    private void itemDeletarFisioterapeutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeletarFisioterapeutaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new fisioterapeutaDeletar().setVisible(true);
    }//GEN-LAST:event_itemDeletarFisioterapeutaActionPerformed

    private void itemDeletarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeletarPacienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new pacienteDeletar().setVisible(true);
    }//GEN-LAST:event_itemDeletarPacienteActionPerformed

    private void itemDeletarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeletarConsultaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new consultaDeletar().setVisible(true);
    }//GEN-LAST:event_itemDeletarConsultaActionPerformed

    private void itemDeletarAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeletarAvaliacaoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new avaliacaoDeletar().setVisible(true);
    }//GEN-LAST:event_itemDeletarAvaliacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JMenuItem itemCadastrarAvaliacao;
    private javax.swing.JMenuItem itemCadastrarConsulta;
    private javax.swing.JMenuItem itemDeletarAvaliacao;
    private javax.swing.JMenuItem itemDeletarClinica;
    private javax.swing.JMenuItem itemDeletarConsulta;
    private javax.swing.JMenuItem itemDeletarFisioterapeuta;
    private javax.swing.JMenuItem itemDeletarPaciente;
    private javax.swing.JMenuItem itemEditarAvaliacao;
    private javax.swing.JMenuItem itemEditarClinica;
    private javax.swing.JMenuItem itemEditarConsulta;
    private javax.swing.JMenuItem itemEditarFisioterapeuta;
    private javax.swing.JMenuItem itemEditarPaciente;
    private javax.swing.JMenuItem itemMenuCadastrarClinica;
    private javax.swing.JMenuItem itemMenuCadastrarFisioterapeuta;
    private javax.swing.JMenuItem itemMenuCadastrarPaciente;
    private javax.swing.JMenuItem itemVisualizarClinica;
    private javax.swing.JMenuItem itemVisualizarConsultas;
    private javax.swing.JMenuItem itemVisualizarFisioterapeutas;
    private javax.swing.JMenuItem itemVisualizarPaciente;
    private javax.swing.JMenuItem itemVisulizarAvaliacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
